services:
  app:
    image: lucastosellolatini/whatsapp-connector:latest
    container_name: whatsapp_connector_app
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - app-network

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/secrets:/etc/nginx/secrets:ro
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/construccion:/var/www/construccion:ro
      - /var/www/lucasweb:/var/www/lucasweb:ro
    networks:
      - app-network
    depends_on:
      - app

  prometheus:
    image: prom/prometheus:v2.47.2
    container_name: prometheus_monitor
    restart: unless-stopped
    ports:
      - '9090:9090'
    volumes:
      # Montamos el DIRECTORIO que contiene la configuración
      - ./prometheus:/etc/prometheus:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - app-network
    depends_on:
      - app

  grafana:
    image: grafana/grafana:10.2.2
    container_name: grafana_dashboard
    restart: unless-stopped
    ports:
      - '3001:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - app-network
    depends_on:
      - prometheus

networks:
  app-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
