version: '3.8'

services:
  app:
    # ¡CAMBIO CLAVE! Ya no construimos, usamos la imagen de Docker Hub.
    image: tunombredeusuario/whatsapp-connector:latest # <-- Reemplazá con tu usuario de Docker Hub
    container_name: whatsapp_connector_app
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - app-network

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge
