prometheus:
  image: prom/prometheus:v2.47.2
  container_name: prometheus_monitor
  restart: unless-stopped
  ports:
    - '9090:9090'
  volumes:
    # Montamos el DIRECTORIO que contiene la configuración
    - ./prometheus:/etc/prometheus:ro
    - prometheus_data:/prometheus
  command:
    - '--config.file=/etc/prometheus/prometheus.yml'
  networks:
    - app-network
  depends_on:
    - app
